version: "3.8"

services:
  uneo_website_frontend:
    image: p2211/uneo_bed_monitor_website_v2:latest   # 測試環境用 develop 分支 build
    container_name: UNEO_WEBSITE
    restart: always
    ports:
      - "8005:3000"
    environment:
      - SOCKETSERVER_IP=192.9.120.100

  watchtower:
    image: containrrr/watchtower:latest
    container_name: watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DOCKER_API_VERSION=1.44
    command: >
      UNEO_WEBSITE
      --interval 30
      --cleanup
      --trace
